
const recruitmentData = 
[ 
    
        {
         "category": "Army",
         "entries": "Tradesman",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "168",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "General Duty (GD)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "45",
         "gender": "Male",
         "height_male": "168",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-21"
        },
        {
         "category": "Navy",
         "entries": "Matric Recruit (MR)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Para Military",
         "entries": "Constable",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "170",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Coast Guard",
         "entries": "Domestic Branch",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "45",
         "gender": "Male",
         "height_male": "163",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Navy",
         "entries": "Senior Secondary Recruit (SSR)",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Short Service Commission (SSC)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": "60",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,December",
         "caste": "Open",
         "age": "18-27"
        },
        {
         "category": "Navy",
         "entries": "Indian Navy Entrance Test (INET)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "60",
         "gender": "Male, Female",
         "height_male": "157",
         "height_female": "148",
         "apply_month": "May,December",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Navy",
         "entries": "Artificer Apprentice (AA)",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "60",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Matric Recruit (MR)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Indian Naval Academy (INA)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Air-Force",
         "entries": "Group X",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "50",
         "gender": "Male",
         "height_male": "152",
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Air-Force",
         "entries": "Group Y",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "50",
         "gender": "Male",
         "height_male": "152",
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Air-Force",
         "entries": "Air Force Common Admission Test (AFCAT)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "60",
         "gender": "Male, Female",
         "height_male": "162",
         "height_female": "162",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Air-Force",
         "entries": "Air Force Academy (AFA)",
         "qualification": "Graduation",
         "stream": "BSC, BSCIT, BE, BTECH",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "20-24"
        },
        {
         "category": "Coast Guard",
         "entries": "Domestic Branch",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Maharashtra Police",
         "entries": "Constable",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "165",
         "height_female": "155",
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "18-28"
        },
        {
         "category": "Army",
         "entries": "Tradesman",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "168",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "General Duty (GD)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "45",
         "gender": "Male",
         "height_male": "168",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-21"
        },
        {
         "category": "Army",
         "entries": "Officers Training Academy (OTA)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male, Female",
         "height_male": "157",
         "height_female": "151",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Army",
         "entries": "Territorial Army (TA)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "157",
         "height_female": "151",
         "apply_month": "June",
         "caste": "Open",
         "age": "18-42"
        },
        {
         "category": "Army",
         "entries": "Indian Military Academy (IMA)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Army",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "45",
         "gender": "Male",
         "height_male": "163",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Navy",
         "entries": "Indian Navy Entrance Test (INET)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "60",
         "gender": "Male, Female",
         "height_male": "157",
         "height_female": "148",
         "apply_month": "May,December",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Navy",
         "entries": "Matric Recruit (MR)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Air-Force",
         "entries": "Group Y",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "50",
         "gender": "Male",
         "height_male": "152",
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Air-Force",
         "entries": "Air Force Common Admission Test (AFCAT)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "60",
         "gender": "Male, Female",
         "height_male": "162",
         "height_female": "162",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Para Military",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "163",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Typing",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "167",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Stenographer",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "165",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Constable",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "170",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Central Armed Police Forces (CAPF)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "157",
         "height_female": "151",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Assistant Commandant",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "157",
         "height_female": "151",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Domestic Branch",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Maharashtra Police",
         "entries": "Constable",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "165",
         "height_female": "155",
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "18-28"
        },
        {
         "category": "Air-Force",
         "entries": "Air Force Academy (AFA)",
         "qualification": "Graduation",
         "stream": "BSC, BSCIT, BE, BTECH",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Air-Force",
         "entries": "Short Service Commission (SSC)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": "60",
         "gender": "Male",
         "height_male": "162",
         "height_female": "162",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "18-27"
        },
        {
         "category": "Para Military",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "163",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Typing",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "167",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Stenographer",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "165",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Constable",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "170",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Central Armed Police Forces (CAPF)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "157",
         "height_female": "151",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Assistant Commandant",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "157",
         "height_female": "151",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Domestic Branch",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Maharashtra Police",
         "entries": "Constable",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "165",
         "height_female": "155",
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "18-28"
        },
        {
         "category": "Army",
         "entries": "Technical Branch",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": 50,
         "gender": "Male",
         "height_male": 167,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "Nursing",
         "qualification": "12th",
         "stream": "Science (PCB)",
         "type": "Non Commission",
         "percentage": 50,
         "gender": "Male",
         "height_male": 163,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "Technical Graduate Course (TGC)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": 60,
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-27"
        },
        {
         "category": "Army",
         "entries": "Tradesman",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 168,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "General Duty (GD)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": 45,
         "gender": "Male",
         "height_male": 168,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-21"
        },
        {
         "category": "Army",
         "entries": "Officers Training Academy (OTA)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male, Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Army",
         "entries": "Territorial Army (TA)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "June",
         "caste": "Open",
         "age": "18-42"
        },
        {
         "category": "Army",
         "entries": "Indian Military Academy (IMA)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Army",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": 45,
         "gender": "Male",
         "height_male": 163,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Navy",
         "entries": "Senior Secondary Recruit (SSR)",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Indian Navy Entrance Test (INET)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": 60,
         "gender": "Male, Female",
         "height_male": 157,
         "height_female": 148,
         "apply_month": "May,December",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Navy",
         "entries": "Artificer Apprentice (AA)",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": 60,
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Matric Recruit (MR)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Indian Naval Academy (INA)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Air-Force",
         "entries": "Group X",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": 50,
         "gender": "Male",
         "height_male": 152,
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Air-Force",
         "entries": "Group Y",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": 50,
         "gender": "Male",
         "height_male": 152,
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Air-Force",
         "entries": "Air Force Common Admission Test (AFCAT)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": 60,
         "gender": "Male, Female",
         "height_male": 162,
         "height_female": 162,
         "apply_month": "July,December",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Air-Force",
         "entries": "Air Force Academy (AFA)",
         "qualification": "Graduation",
         "stream": "BSC, BSCIT, BE, BTECH",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Para Military",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 163,
         "height_female": 157,
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Typing",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 167,
         "height_female": 157,
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Stenographer",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 165,
         "height_female": 157,
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Constable",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 170,
         "height_female": 157,
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Central Armed Police Forces (CAPF)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Assistant Commandant",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Navik GD",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Coast Guard",
         "entries": "Domestic Branch",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Maharashtra Police",
         "entries": "Constable",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 165,
         "height_female": 155,
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "18-28"
        },
        {
         "category": "Army",
         "entries": "Technical Branch",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": 50,
         "gender": "Male",
         "height_male": 167,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "Nursing",
         "qualification": "12th",
         "stream": "Science (PCB)",
         "type": "Non Commission",
         "percentage": 50,
         "gender": "Male",
         "height_male": 163,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "Technical Graduate Course (TGC)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": 60,
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-27"
        },
        {
         "category": "Army",
         "entries": "Tradesman",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 168,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "General Duty (GD)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": 45,
         "gender": "Male",
         "height_male": 168,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-21"
        },
        {
         "category": "Army",
         "entries": "Officers Training Academy (OTA)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male, Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Army",
         "entries": "Territorial Army (TA)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "June",
         "caste": "Open",
         "age": "18-42"
        },
        {
         "category": "Army",
         "entries": "Indian Military Academy (IMA)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Army",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": 45,
         "gender": "Male",
         "height_male": 163,
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Navy",
         "entries": "Senior Secondary Recruit (SSR)",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Short Service Commission (SSC)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": 60,
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,December",
         "caste": "Open",
         "age": "18-27"
        },
        {
         "category": "Navy",
         "entries": "Indian Navy Entrance Test (INET)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": 60,
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Navy",
         "entries": "Matric Recruit (MR)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-20"
        },
        {
         "category": "Air-Force",
         "entries": "AFCAT",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": 60,
         "gender": "Male,Female",
         "height_male": 162,
         "height_female": 162,
         "apply_month": "December",
         "caste": "Open",
         "age": "20-24"
        },
        {
         "category": "Air-Force",
         "entries": "NDA (National Defence Academy)",
         "qualification": "12th",
         "stream": "Science (PCM)",
         "type": "Commission",
         "percentage": 45,
         "gender": "Male",
         "height_male": 162,
         "height_female": "NULL",
         "apply_month": "June,December",
         "caste": "Open",
         "age": "16-19"
        },
        {
         "category": "Air-Force",
         "entries": "Airmen Group X & Y",
         "qualification": "12th",
         "stream": "Science (PCM)",
         "type": "Non Commission",
         "percentage": 50,
         "gender": "Male",
         "height_male": 152.5,
         "height_female": "NULL",
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Air-Force",
         "entries": "Meteorology Entry",
         "qualification": "Post Graduation",
         "stream": "Meteorology",
         "type": "Commission",
         "percentage": 50,
         "gender": "Male,Female",
         "height_male": 157.5,
         "height_female": 157.5,
         "apply_month": "January,July",
         "caste": "Open",
         "age": "20-26"
        },
        {
         "category": "Para Military",
         "entries": "Central Armed Police Forces (CAPF)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Assistant Commandant",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Domestic Branch",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Maharashtra Police",
         "entries": "Constable",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 165,
         "height_female": 155,
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "18-28"
        },
        {
         "category": "Para Military",
         "entries": "Constable",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "170",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Central Armed Police Forces (CAPF)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "157",
         "height_female": "151",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Assistant Commandant",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "157",
         "height_female": "151",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Yantrik",
         "qualification": "Diploma",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Coast Guard",
         "entries": "Navik GD",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Coast Guard",
         "entries": "Domestic Branch",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Maharashtra Police",
         "entries": "Constable",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "165",
         "height_female": "155",
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "18-28"
        },
        {
         "category": "Army",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "45",
         "gender": "Male",
         "height_male": "163",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Navy",
         "entries": "Senior Secondary Recruit (SSR)",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Para Military",
         "entries": "Stenographer",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "165",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Navy",
         "entries": "Matric Recruit (MR)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Indian Naval Academy (INA)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Air-Force",
         "entries": "Group X",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": 50,
         "gender": "Male",
         "height_male": 152,
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Air-Force",
         "entries": "Group Y",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": 50,
         "gender": "Male",
         "height_male": 152,
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Air-Force",
         "entries": "Air Force Common Admission Test (AFCAT)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": 60,
         "gender": "Male, Female",
         "height_male": 162,
         "height_female": 162,
         "apply_month": "July,December",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Air-Force",
         "entries": "Air Force Academy (AFA)",
         "qualification": "Graduation",
         "stream": "BSC, BSCIT, BE, BTECH",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-24"
        },
        {
         "category": "Air-Force",
         "entries": "Short Service Commission (SSC)",
         "qualification": "Graduation",
         "stream": "BE, BTECH",
         "type": "Commission",
         "percentage": 60,
         "gender": "Male",
         "height_male": 162,
         "height_female": 162,
         "apply_month": "July,December",
         "caste": "Open",
         "age": "18-27"
        },
        {
         "category": "Para Military",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 163,
         "height_female": 157,
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Typing",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 167,
         "height_female": 157,
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Stenographer",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 165,
         "height_female": 157,
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Constable",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 170,
         "height_female": 157,
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Central Armed Police Forces (CAPF)",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Assistant Commandant",
         "qualification": "Graduation",
         "stream": "Others",
         "type": "Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 157,
         "height_female": 151,
         "apply_month": "July,November",
         "caste": "Open",
         "age": "18-25"
        },
        {
         "category": "Coast Guard",
         "entries": "Yantrik",
         "qualification": "Diploma",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Coast Guard",
         "entries": "Navik GD",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Coast Guard",
         "entries": "Domestic Branch",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": 157,
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Maharashtra Police",
         "entries": "Constable",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": 165,
         "height_female": 155,
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "18-28"
        },
        {
         "category": "Army",
         "entries": "Tradesman",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "168",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Army",
         "entries": "General Duty (GD)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "45",
         "gender": "Male",
         "height_male": "168",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-21"
        },
        {
         "category": "Army",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "45",
         "gender": "Male",
         "height_male": "163",
         "height_female": "NULL",
         "apply_month": "Open Rally",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Navy",
         "entries": "Senior Secondary Recruit (SSR)",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Artificer Apprentice (AA)",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "60",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Navy",
         "entries": "Matric Recruit (MR)",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "16-21"
        },
        {
         "category": "Air-Force",
         "entries": "Group X",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "50",
         "gender": "Male",
         "height_male": "152",
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Air-Force",
         "entries": "Group Y",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "50",
         "gender": "Male",
         "height_male": "152",
         "height_female": "NULL",
         "apply_month": "July,December",
         "caste": "Open",
         "age": "17-21"
        },
        {
         "category": "Para Military",
         "entries": "Store Keeper Technical (SKT)",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "163",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Typing",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "167",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Stenographer",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "165",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Para Military",
         "entries": "Constable",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "170",
         "height_female": "157",
         "apply_month": "Anytime",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Coast Guard",
         "entries": "Navik GD",
         "qualification": "12th",
         "stream": "Science (PCM),Science (PCB),Science (PCMB)",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Coast Guard",
         "entries": "Domestic Branch",
         "qualification": "10th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male",
         "height_male": "157",
         "height_female": "NULL",
         "apply_month": "June,November",
         "caste": "Open",
         "age": "18-23"
        },
        {
         "category": "Maharashtra Police",
         "entries": "Constable",
         "qualification": "12th",
         "type": "Non Commission",
         "percentage": "NULL",
         "gender": "Male,Female",
         "height_male": "165",
         "height_female": "155",
         "apply_month": "Once a year",
         "caste": "Open",
         "age": "18-28"
        }
       

];


document.getElementById('qualification').addEventListener('change', function() {
const selectedValue = this.value;
const graduationOptions = document.getElementById('graduation-options');

if (selectedValue === 'graduation') {
  graduationOptions.style.display = 'block';
} else {
  graduationOptions.style.display = 'none';
}
});

document.getElementById('check-eligibility').addEventListener('click', function() {
const age = parseInt(document.getElementById('age').value);
const gender = document.getElementById('gender').value;
const qualification = document.getElementById('qualification').value;
const graduationStream = document.getElementById('graduation-stream').value;

let matchingCategories = [];

for (const entry of recruitmentData) {
  const entryAgeRange = entry.age.split('-');
  const minAge = parseInt(entryAgeRange[0]);
  const maxAge = parseInt(entryAgeRange[1]);

  if (
    age >= minAge && age <= maxAge &&
    entry.gender.includes(gender) &&
    ((qualification !== 'graduation' && entry.qualification === qualification) ||
    (qualification === 'graduation' && entry.stream && entry.stream.split(', ').includes(graduationStream)))
  ) {
    matchingCategories.push(entry);
  }
}

const resultElement = document.getElementById('result');
if (matchingCategories.length > 0) {
  console.log('Matching Categories:', matchingCategories);

  const formattedData = matchingCategories.map(entry => {
    return Object.keys(entry).map(key => {
      return `${key}: ${entry[key]}`;
    }).join('\n');
  }).join('\n\n');

  resultElement.textContent = formattedData;
} else {
  console.log('No matching categories found.');
  resultElement.textContent = 'No matching categories found.';
}
});
